# Generated by Django 3.2.6 on 2021-08-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumulus', '0002_rename_password_hash_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
