# Generated by Django 3.2.6 on 2021-08-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumulus', '0003_alter_member_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='member_id',
            new_name='member',
        ),
    ]
