# Generated by Django 3.2.6 on 2021-08-23 08:09

from django.db import migrations, models
import nanoid.generate


class Migration(migrations.Migration):

    dependencies = [
        ('cumulus', '0004_rename_member_id_project_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=nanoid.generate, editable=False, max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thundersupport',
            name='statusCode',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
