# Generated by Django 3.2.6 on 2021-08-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumulus', '0005_auto_20210823_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thunder',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='thundersource',
            old_name='thunder_id',
            new_name='thunder',
        ),
    ]
