# Generated by Django 3.2.6 on 2021-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumulus', '0006_auto_20210831_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='thunder',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
