# Generated by Django 3.2.6 on 2021-10-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumulus', '0007_thunder_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
