# Generated by Django 3.2.6 on 2021-10-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumulus', '0008_alter_project_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
